### ISSUE TITLE
Check Tab parsed successfully

### ISSUE THREAD

**Issue by MrChros** [stdtabs/phptabs#15]
Hi Landrok,
let me wish you a happy new year first! May it be as productive as the last  one. :)

Quick question from my side:
I'm updating my website to use the current version 1.0.4 of PhpTabs. In former versions it was possible to check if an gp5-file has been parsed successfully by checking:

```
$tablature = new PhpTabs("file.gp5");
if ($tablature->hasError()) { ... }
```

In the current version this method does not exist anymore. Which way is intended to check if a file has been parsed succussfully?

Best regards,
MrChros

**Comment by landrok** [comment]
Hey MrChros,

Thank you! I wish you a happy and healthy new year too.

Starting from 1.0, there is no more getError(), hasError() and setError() methods. I put a (too) little word on it in the [changelog](https://github.com/stdtabs/phptabs/blob/master/CHANGELOG.md#removed).

All errors are now throwing a PHP Exception, you must use  a try... catch to handle them.

```php
try {
    $tablature = new PhpTabs("file.gp5");
} catch(Exception $e) {
    // There is an error
    echo $e->getMessage();
    die;
}

// File has been successfully parsed
echo $tablature->getName();
```

The reason is that in the previous releases, there may be inconsistent behaviors when an error occurred depending on where it was spotted or if the debug mode was activated.

Regards,
Landrok

**Comment by MrChros** [comment]
Hi,
thanks for the quick answer.
Working great!

Best regards,
MrChros
