### ISSUE TITLE
I can't not to calculator time in second for note one by one, can you help us ?

### ISSUE THREAD

**Issue by motniemtin** [stdtabs/phptabs#5]
Music in 6/8. I tried to plus all notes length but it alway # with 2880 length of measure
Please view full json on: https://jsoneditoronline.org/?id=ad299386fc7b439f888296e64eec3145

**Comment by landrok** [comment]
Hi,

In order to calculate measure duration, you should use beat voices instead (2 voices by beat).

This way, you can sum all beats durations and get measure duration.

This [commit](https://github.com/stdtabs/phptabs/commit/62cd604bf3824fa6a9c03deb298c53798f08cd46) adds a shortcut method to do that.

Thanks to your question and the previous one, I wrote a [tutorial](https://stdtabs.github.io/calculate-measure-and-beat-durations-in-seconds.html#beat-duration) to explain how to do that.

Hope this helps

**Comment by landrok** [comment]
Look good to you?

**Comment by motniemtin** [comment]
Thank you very much, It's useful
